language: rust
os: linux
dist: xenial

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)

script:
  - cd book && mdbook build && mdbook test

deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages
