[book]
authors = ["cstanze"]
language = "en"
multilingual = false
src = "src"
title = "Blossom Lang"

[output.html]

[output.linkcheck]
optional = true # linkcheck occurs on the dev machine. no need to check again.
