

#ifndef COMPILER_CONFIG_HPP
#define COMPILER_CONFIG_HPP

#define BLOSSOM_VERSION_MAJOR 0
#define BLOSSOM_VERSION_MINOR 0
#define BLOSSOM_VERSION_PATCH 3

#define BUILD_CXX_COMPILER "Clang 11.0.3.11030032"
#define BUILD_DATE "Fri May 15, 2020 at 01:40:10"

#endif // COMPILER_CONFIG_HPP
